import { Ionicons, MaterialCommunityIcons } from "@expo/vector-icons";

export interface Category {
  name: string;
  image: any;
  iconName: string;
  iconFamily: "Ionicons" | "MaterialCommunityIcons";
  href: string;
  value: string;
}

export const CATEGORIES: Category[] = [
  {
    name: "Home Décor",
    image: require("../assets/images/categories/home decor/decor.jpg"),
    iconName: "home-outline",
    iconFamily: "Ionicons",
    href: "/shop?cat=home-decor",
    value: "home-decor",
  },
  {
    name: "Kitchenware",
    image: require("../assets/images/categories/kitchenware/kitchen.jpg"),
    iconName: "restaurant-outline",
    iconFamily: "Ionicons",
    href: "/shop?cat=kitchenware",
    value: "kitchenware",
  },
  {
    name: "Books & Stationery",
    image: require("../assets/images/categories/stationery/stationery.jpg"),
    iconName: "book-outline",
    iconFamily: "Ionicons",
    href: "/shop?cat=books-stationery",
    value: "books-stationery",
  },
  {
    name: "Baby Products",
    image: require("../assets/images/categories/baby products/baby.jpg"),
    iconName: "baby-face-outline",
    iconFamily: "MaterialCommunityIcons",
    href: "/shop?cat=baby-products",
    value: "baby-products",
  },
  {
    name: "Toys & Games",
    image: require("../assets/images/categories/toys/toys.jpg"),
    iconName: "game-controller-outline",
    iconFamily: "Ionicons",
    href: "/shop?cat=toys-games",
    value: "toys-games",
  },
  {
    name: "Sports & Fitness",
    image: require("../assets/images/categories/sports/sports.jpg"),
    iconName: "barbell-outline",
    iconFamily: "Ionicons",
    href: "/shop?cat=sports-fitness",
    value: "sports-fitness",
  },
  {
    name: "Computer Accessories",
    image: require("../assets/images/categories/computer accessories/computer.jpg"),
    iconName: "desktop-outline",
    iconFamily: "Ionicons",
    href: "/shop?cat=computer-accessories",
    value: "computer-accessories",
  },
  {
    name: "Office Supplies",
    image: require("../assets/images/categories/office supplies/office.jpg"),
    iconName: "briefcase-outline",
    iconFamily: "Ionicons",
    href: "/shop?cat=office-supplies",
    value: "office-supplies",
  },
  {
    name: "Digital Products",
    image: require("../assets/images/categories/digital products/digital.jpg"),
    iconName: "laptop-outline",
    iconFamily: "Ionicons",
    href: "/shop?cat=digital-products",
    value: "digital-products",
  },
  {
    name: "Automotive",
    image: require("../assets/images/categories/automotive/automotive.jpg"),
    iconName: "car-outline",
    iconFamily: "Ionicons",
    href: "/shop?cat=automotive-accessories",
    value: "automotive-accessories",
  },
  {
    name: "Pet Supplies",
    image: require("../assets/images/categories/pet/pet.jpg"),
    iconName: "paw-outline",
    iconFamily: "Ionicons",
    href: "/shop?cat=pet-supplies",
    value: "pet-supplies",
  },
  {
    name: "Health Products",
    image: require("../assets/images/categories/health/health.jpg"),
    iconName: "medical-outline",
    iconFamily: "Ionicons",
    href: "/shop?cat=health-products",
    value: "health-products",
  },
  {
    name: "Craft & DIY",
    image: require("../assets/images/categories/craft/craft.jpg"),
    iconName: "color-palette-outline",
    iconFamily: "Ionicons",
    href: "/shop?cat=craft-diy",
    value: "craft-diy",
  },
  {
    name: "Events & Parties",
    image: require("../assets/images/categories/events and parties/event.jpg"),
    iconName: "party-popper",
    iconFamily: "MaterialCommunityIcons",
    href: "/shop?cat=event-party-supplies",
    value: "event-party-supplies",
  },
  {
    name: "Clothing & Apparel",
    image: require("../assets/images/categories/clothing/clothing.jpg"),
    iconName: "shirt-outline",
    iconFamily: "Ionicons",
    href: "/shop?cat=clothing-apparel",
    value: "clothing-apparel",
  },
  {
    name: "Footwear",
    image: require("../assets/images/categories/footwear/footwear.jpg"),
    iconName: "footsteps-outline",
    iconFamily: "Ionicons",
    href: "/shop?cat=footwear",
    value: "footwear",
  },
  {
    name: "Fashion Accessories",
    image: require("../assets/images/categories/fashion/fashionaccessories.jpg"),
    iconName: "watch-outline",
    iconFamily: "Ionicons",
    href: "/shop?cat=fashion-accessories",
    value: "fashion-accessories",
  },
  {
    name: "Electronics",
    image: require("../assets/images/categories/electronics/electronics.jpg"),
    iconName: "tv-outline",
    iconFamily: "Ionicons",
    href: "/shop?cat=electronics",
    value: "electronics",
  },
  {
    name: "Phone Accessories",
    image: require("../assets/images/categories/phone accessories/phones.jpg"),
    iconName: "phone-portrait-outline",
    iconFamily: "Ionicons",
    href: "/shop?cat=phone-accessories",
    value: "phone-accessories",
  },
  {
    name: "Home Appliances",
    image: require("../assets/images/categories/home appliances/home.jpg"),
    iconName: "flash-outline",
    iconFamily: "Ionicons",
    href: "/shop?cat=home-appliances",
    value: "home-appliances",
  },
  {
    name: "Beauty Products",
    image: require("../assets/images/categories/beauty products/beauty.jpg"),
    iconName: "sparkles-outline",
    iconFamily: "Ionicons",
    href: "/shop?cat=beauty-products",
    value: "beauty-products",
  },
  {
    name: "Personal Care",
    image: require("../assets/images/categories/personal care/personal.jpg"),
    iconName: "heart-outline",
    iconFamily: "Ionicons",
    href: "/shop?cat=personal-care",
    value: "personal-care",
  },
  {
    name: "Watches & Jewelry",
    image: require("../assets/images/categories/jewelary/watches.jpg"),
    iconName: "watch-outline",
    iconFamily: "Ionicons",
    href: "/shop?cat=watches-jewelry",
    value: "watches-jewelry",
  },
  {
    name: "Groceries & Foods",
    image: require("../assets/images/categories/groceries and foods/groceries.jpg"),
    iconName: "cart-outline",
    iconFamily: "Ionicons",
    href: "/shop?cat=groceries-packaged-foods",
    value: "groceries-packaged-foods",
  },
  {
    name: "Furniture",
    image: require("../assets/images/categories/furniture/furniture.jpg"),
    iconName: "bed-outline",
    iconFamily: "Ionicons",
    href: "/shop?cat=furniture",
    value: "furniture",
  },
  {
    name: "Farm Products",
    image: require("../assets/images/categories/farm products/farm.jpg"),
    iconName: "leaf-outline",
    iconFamily: "Ionicons",
    href: "/shop?cat=farm-products",
    value: "farm-products",
  },
];
